variables:
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

.docker-build-base:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - Dockerfile

# Native amd64 build
docker-build:amd64:
  extends: .docker-build-base
  script:
    - docker build --platform linux/amd64 --pull -t "$DOCKER_IMAGE_NAME-amd64" .
    - docker push "$DOCKER_IMAGE_NAME-amd64"
    # Tag and push latest for main branch
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi

  tags:
    - builds